### ISSUE TITLE
Bug - OSError: [WinError 10038]

### ISSUE THREAD

**Issue by chameeradesilva** [nemec/snapchat-map-scraper#1]
After running the "Review media" scrip, the below issue occurred.

Traceback (most recent call last):
  File "story_downloader.py", line 356, in <module>
    review(args.database, args.player, args.label)
  File "story_downloader.py", line 266, in review
    while select.select([sys.stdin.fileno()], [], [], 0.0)[0]:
OSError: [WinError 10038] An operation was attempted on something that is not a socket

Note - Media folder created. and also when running the export command, there won't be any media data for the export folder but data exist in media directory, not the export.

**Comment by nemec** [comment]
Thanks for the report, apparently flushing the buffer that way doesn't work on Windows. It was meant to keep you from accidentally skipping through videos if you hold down on the enter key too long, but the code should work fine without it. I've added a condition to skip that bit if you're running Windows, try getting the latest code and running it again.
