### ISSUE TITLE
Problem with the function scrape_location

### ISSUE THREAD

**Issue by ili403** [nemec/snapchat-map-scraper#4]
Hello

When I run the program, I can add a location to the database but when I try to run the function "scrape_location" for scraping media, it raises a KeyError with prefixURL since yesterday. 
Can you help me fixing this?

Thanks!!

**Comment by AntDeb98** [comment]
In "def scrape_location" try to use :

media = info.get('streamingMediaInfo')
thumbnail = info.get('streamingThumbnailInfo')
preview_url = None
media_url = None
overlay_url = None

if media:
            if media.get('mediaUrl'): 
                media_url = media['mediaUrl']
            if media.get('overlayUrl'): 
                overlay_url = media['overlayUrl']
                if not overlay_url.endswith('png'):
                    print(f'Overlay url: {overlay_url}')
if thumbnail:
            preview_url = thumbnail['infos'][0]['thumbnailUrl']

**Comment by nemec** [comment]
Hi @ili403, thank you for mentioning this! I've pushed a new change that should fix this. Please download the code again or run `git pull` to get the latest.
